---
services:
  dev:
    build: dev1
    volumes:
      - magictube:/boxfuse/boxfuse-sample-java-war-hello/target:z

  prod:
    image: tomcat9-slim
    ports: 
      - "8080:8080"
    volumes:
      - magictube:/usr/local/tomcat/webapps:z
    command: ["/usr/local/tomcat/bin/catalina.sh", "run"]
    depends_on:
      - dev

version: '3'
volumes:
  magictube: