version '3'
services:
  dev:
    build: dev1
    volumes:
      - magictube:/boxfuse/boxfuse-sample-java-war-hello/target:z

  prod:
    image: prod1
    ports: 
      - "8080:8080"
    volumes:
      - magictube:/opt/tomcat/webapps/

volumes:
  magictube: