---
services:
  dev:
    build: dev1
    volumes:
      - magictube:/boxfuse/boxfuse-sample-java-war-hello/target:z

  prod:
    image: davidcaste/alpine-tomcat:latest
    ports: 
      - "8080:8080"
    volumes:
      - magictube:/opt/tomcat/webapps/
    depends_on:
      - dev

version: '3'
volumes:
  magictube: